### ISSUE TITLE
CRAN checklist

### ISSUE THREAD

**Issue by RamiKrispin** [Covid19R/covid19italy#3]
- [x] Update the readme

- [x] Update the package site

- [x] Update the package vignette

- [x] Update the package news
